### ISSUE TITLE
Dualize a large model with many constraints each have sigma computation

### ISSUE THREAD

**Issue by jafar75** [jump-dev/Dualization.jl#101]
Hi there

I'm new to Julia and library. I wanna to dualize a large LP in network resource allocation. LP has many constraints each has written as sum (sigma) of variables. 
I wonder Dualization.jl can dualize these type of LPs. Because tests are rather simple LPs and # of vars and constraints are small.

Thanks

**Comment by guilhermebodin** [comment]
It surely can, It can dualize problems up to cone quadratic programs, linear programs are included in this specification.
