### ISSUE TITLE
print the variables name and constraints each variable is involved in

### ISSUE THREAD

**Issue by jafar75** [jump-dev/Dualization.jl#102]
Hi there, 

I want to get name of variables and also constraints in form, to find easily each var in any constraints it appers.
Is there any functionality/test for this?

regards,

**Comment by guilhermebodin** [comment]
Hi @jafar75 

You can try to use the `dual_name` keyword argument. Here is an example https://jump.dev/Dualization.jl/stable/examples/#Naming-the-dual-variables-and-dual-constraints-1

If this is not what you are looking for please try to write a minimal example so we can help

**Comment by jafar75** [comment]
well, I have a LP like bellow, x(p) is decision variable and others are constant. All are reals and non-negative.

![image](https://user-images.githubusercontent.com/22050512/103618628-86edc800-4f45-11eb-9c42-4581c24a63d2.png)

I want to print its dual (number of variables and formation of constraints) like this:

![image](https://user-images.githubusercontent.com/22050512/103618878-ef3ca980-4f45-11eb-807b-73467292d023.png)
![image](https://user-images.githubusercontent.com/22050512/103618925-0a0f1e00-4f46-11eb-84d9-0d17e3178fe5.png)

**Comment by guilhermebodin** [comment]
Well, you cannot rename the variables entirely, the dual variables must be a prefix of the names of the constraints. So having a dual variable purely named y_e is not possible. Give it a try in the example :)

**Comment by jafar75** [comment]
Thanks, 

But, I mean want to something like `iterating` over constraints of dual LP and print them. Maybe I have a mistake and the exact names are not important.

regards,

**Comment by guilhermebodin** [comment]
maybe this should solve the problem
```julia
using JuMP, Dualization

model = Model()
@variable(model, x)
@variable(model, y)
@variable(model, z)
@constraint(model, con1, x + y >= 1)
@constraint(model, con2, y + z >= 1)
@constraint(model, con3, x + z >= 1)
@objective(model, Min, x + y + z)

dual_model = dualize(model; dual_names = DualNames("dual", ""))
print(dual_model)
Max dualcon2_1 + dualcon3_1 + dualcon1_1
Subject to
 x : dualcon1_1 + dualcon3_1 = 1.0
 y : dualcon1_1 + dualcon2_1 = 1.0
 z : dualcon2_1 + dualcon3_1 = 1.0
 dualcon1_1 ≥ 0.0
 dualcon2_1 ≥ 0.0
 dualcon3_1 ≥ 0.0
```

**Comment by jafar75** [comment]
Thanks. it sounds great.

Would you know where can I find examples to define vars, cons, objective using arrays, matrices or sigma for instance?

**Comment by guilhermebodin** [comment]
probably the JuMP documentation https://jump.dev/JuMP.jl/stable/, if you have more doubts about JuMP I strongly recommend posting on Julia discourse on the Maathmatical Optimization tag https://discourse.julialang.org/c/domain/opt/13.

**Comment by jafar75** [comment]
thanks my friend,
