### ISSUE TITLE
Possible wrong infomation on README

### ISSUE THREAD

**Issue by guilhermebodin** [jump-dev/Dualization.jl#153]
A user emailed me saying that informations on the README concerning the form used by each solver were wrong.

He said that SeDuMi used the standard form and that Mosek accepted both forms, kind of implying that it should not be placed on one of the forms.

**Comment by odow** [comment]
Mosek only started allowing `Ax + b in K` in Mosek 10: https://docs.mosek.com/10.0/releasenotes/changes.html, so it could probably be placed in either list.

@Blegat can correct me, but SeDuMi.jl implements the Geometric form:

https://github.com/jump-dev/SeDuMi.jl/blob/ad681e3c3bc893fdd63d1a867bf1f8dee12a94c1/src/MOI_wrapper.jl#L123-L137

**Comment by blegat** [comment]
SeDuMi.jl does the geometric one. For Mosek, they know supports both indeed and soon they will use the geometric one only.
It does not make sense to talk about the form supported by SeDuMi itself, it's just a matter of consider the `A` matrix of its transpose so the user might have meant the SeDuMi solver itself.
For the MOI wrapper, it's well defined and the it's the geometric form.

**Comment by odow** [comment]
Closed by #157 157
