### ISSUE TITLE
Performance of creating equality constraints

### ISSUE THREAD

**Issue by guilhermebodin** [jump-dev/Dualization.jl#66]
To create equality constraints we must evaluate the `set_dot` function. Today we instantiate a vector of the size of the set. Don't know if changing it to a sparse vector would help in all cases.

```julia
function set_dot(i::Int, s::MOI.AbstractVectorSet, T::Type)
    vec = zeros(T, MOI.dimension(s))
    vec[i] = one(T)
    return MOIU.set_dot(vec, vec, s)
end
```

**Comment by joaquimg** [comment]
another bottleneck is looping many times over all constraints, we can solve this second problem by building all constraints at the same time before adding them.
