### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by guilhermebodin** [jump-dev/Dualization.jl#88]
docs appear to be unformatted, raw latex commands are appearing instead of the compiled equation. Fix that the `dual_set` function is no longer from `Dualization.jl`

**Comment by trathi05** [comment]
I have just started using the Dualization package and was going through the manual. It still shows a lot of unformatted, raw latex commands. Any updates on fixing this?

**Comment by blegat** [comment]
It's fixed on master, the dev documentation works, we just need a new release. I'll do one once https://github.com/jump-dev/Dualization.jl/pull/98 is done.

**Comment by blegat** [comment]
Resolved by release v0.3.3
