### ISSUE TITLE
Possibility to change the objective function in dualized model

### ISSUE THREAD

**Issue by martincornejo** [jump-dev/Dualization.jl#90]
From a [discussion](https://discourse.julialang.org/t/jump-dual-model-formulation-and-impact-on-performance/39124/2?u=martincornejo) in the Julia discourse: Currently Dualization.jl doesn't support changing the objective function without dropping the model and dualizing again. That feature would bring a performance improvement.

**Comment by anavarro01** [comment]
Hi, i have a question about this. What do you mean about "dropping the model"?
I'm trying to solve a two stage robust problem, so i need to dualize the model and then change a parameter into a variable in the objective function. Is there a way to do this with the package?

Thanks in advance

**Comment by martincornejo** [comment]
Better ask directly in the discourse discussion (link above). That platform is more suited for questions.

**Comment by guilhermebodin** [comment]
I will come back to the open PR this week, it is already implemented but it didn`t pass some tests for compatibility

**Comment by guilhermebodin** [comment]
@martincornejo Does this version solves the problem?

**Comment by martincornejo** [comment]
Sorry for the late reply. So this PR introduced the `MOI.modify(::DualOptimizer{T}, ...)` method. I've been struggling a bit understanding how to make use of it.

Suposse I have a `GenericQuadExpr{Float64,VariableRef}` with the new terms of the objective function. How exactly should I feed them in in order for them to modify the objective function?

**Comment by guilhermebodin** [comment]
You should be able to use the JuMP function `set_objective_coefficient`

```julia
    model = Model(GLPK_DUAL_FACTORY)
    @variable(model, x[1:2] >= 0)
    @constraint(model, 2x[1] + x[2] <= 4)
    @constraint(model, x[1] + 2x[2] <= 4)
    @objective(model, Min, -4x[1] + -3x[2])
    optimize!(model)
    @test objective_value(model) ≈ -28/3
    set_objective_coefficient(model, x[1], -5.0)
    optimize!(model)
    @test objective_value(model) ≈ -10.6666666666
```

**Comment by martincornejo** [comment]
Something like this?

```julia
# new_objective: GenericQuadExpr{Float64,VariableRef}

# For the affine terms:
for (v, t) in new_objective.aff.terms
           scc = MOI.ScalarCoefficientChange(index(v), t)
           MOI.modify(
                model.moi_backend.optimizer, 
                MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}(), 
                scc
           )
end
```

But not sure how to `modify` the quadratic terms

**Comment by guilhermebodin** [comment]
hmm I am going to have a look if this works with quadratic terms, could you post a minimal example of your problem?

**Comment by martincornejo** [comment]
```julia
using LinearAlgebra
using JuMP
using MosekTools, Dualization

m = model(dual_optimizer(Mosek.Optimizer))

@variable(m, X[1:2, 1:2])

@constraint(m, X ∈ PSDCone())

λ = rand(2,2)
r = rand(2,2)
ρ = rand()


@objective(m, Min, dot(λ, r - X) + ρ * sum(x->x^2, r - X))
optimize!(m)
```

I should be able to change any λ, r or ρ

**Comment by guilhermebodin** [comment]
This PR solves the `dot` part 

```julia
m = Model(dual_optimizer(SCS.Optimizer))
@variable(m, X[1:2, 1:2])
@constraint(m, X ∈ PSDCone())
λ = rand(2,2)
r = rand(2,2)
ρ = rand()
@objective(m, Min, dot(λ, r - X) + ρ * sum(x->x^2, r - X))
optimize!(m)
objective_function(m)
set_objective_coefficient(m, X[1, 1], -5.0)
optimize!(m)
```
I am investigating how to change the quadratic terms.

**Comment by guilhermebodin** [comment]
@martincornejo https://discourse.julialang.org/t/modifying-coefficient-of-quadratic-term-in-objective-function/51622 

Unfortunately, I think we can only modify the linear parts of the objective function without calling `@objective`. Whenever you update the objective function dual_optimizer will have to dualize the problem

**Comment by martincornejo** [comment]
Too bad, I guess I'll open an issue in MathOptInterface to add support for quadratic terms in `MOI.ScalarCoefficientChange`. I think it's a feature that many would benefit from.

Thanks!
