### ISSUE TITLE
Sign to revise in dualization?

### ISSUE THREAD

**Issue by davide-f** [jump-dev/Dualization.jl#95]
Dear developers,

While using BilevelJuMP, I experienced some problems detailed in https://github.com/joaquimg/BilevelJuMP.jl/issues/82 that may be due to package Dualization.
In particular, I believe that in my problem the sign of the constant that the dualization package performs is the opposite the one it should be and maybe the inequality constraint may be checked as although the variables are non-negative the constraints are equalities.

The code below reproduces the lower problem of the one described in the previous link.
The dual calculation of the problem of the link are detailed in the pdf file here attached
[bug_check.pdf](https://github.com/jump-dev/Dualization.jl/files/5045178/bug_check.pdf), along with the output: the dual dual.lp
[dual_lp.txt](https://github.com/jump-dev/Dualization.jl/files/5045102/dual_lp.txt)

```
using JuMP, Gurobi, Dualization

model = Model(Gurobi.Optimizer)

p = 0

@variable(model, 0 <= p_N[1:2] <= 10)
@variable(model, 0 <= m_P[1:2] <= 10)
@variable(model, 0 <= m_N[1:2] <= 10)

@constraint(model, con_b[i=1:2], - p_N[i] + m_P[i] - m_N[i] == - 3*i)
@objective(model, Max, sum( - p_N[i]*0.1 - m_N[i]*(p + 0.01) + m_P[i]*(p - 0.003) for i in 1:2))

dual_problem = dualize(model, dual_names = DualNames("dual_", "dual_"))

write_to_file(dual_problem, "dual.lp")
```

Does it make sense to you?

**Comment by davide-f** [comment]
I believe the change in sign occurs here.
https://github.com/jump-dev/Dualization.jl/blob/2875b40b7b2c9da1e2a980a975ce45ed941325f5/src/dual_equality_constraints.jl#L7

The calculations of all constraints of the package is coherent with the "max" convention; minimization problems (min obj) seem to be converted in maximization problems by using the equivalent "max -obj".
However, the choice of the sign is choosen according to the dual objective sense, rather than the primal one.
I don't know the software fully, so maybe the problem may be somewhere else, but I hope to have given you some hints.

**Comment by odow** [comment]
JuMP doesn't use the textbook version of linear programming duality: https://jump.dev/JuMP.jl/v0.21.1/constraints/#constraint_duality-1

Here are the finer details: https://jump.dev/MathOptInterface.jl/stable/apimanual/#Duals-1
